### ISSUE TITLE
extra-build-args seems broken in 8.0.0

### ISSUE THREAD

**Issue by iandelahorne** [CircleCI-Public/aws-ecr-orb#182]
### Orb version
8.0.0

### What happened
We use build args to pass arguments into the container build process. For example, we build our own base images off upstream containers with our own customizations added in. To support multiple versions of the upstream container with the same Dockerfiles, we do the following in a dockerfile for our python container:
```
ARG BASE_VERSION=3.8
FROM python:${BASE_VERSION}

RUN apt update && apt install -y jq libmaxminddb-dev libmaxminddb0 mmdb-bin
```

In our CircleCI job, we do the following:

```yaml
jobs:
  build_python_base:
    parameters:
      python_version:
        description: Python version tag to build a container from and push as
        type: string
        default: "3.8"
    executor: aws-ecr/default
    steps:
      - aws-ecr/ecr-login
      - aws-ecr/build-image:
          tag: << parameters.python_version >>
          repo: python_base
          extra-build-args: "--build-arg BASE_VERSION=<<parameters.python_version>>"

workflows:
  main:
    jobs:
      - build_python_base:
          matrix:
            parameters:
              python_version: ["3.8", "3.9", "3.10"]
```

This allows us to build base images for 3.8, 3.9 and 3.10 all from the same definition, and worked great in 7.3.0

However, in 8.0.0,  the build fails with the following output:

```
unknown flag: --build-arg BASE_VERSION
See 'docker buildx build --help'.

Exited with code exit status 125
```
After trying without passing parameters and just using a static 
`extra-build-args: "--build-arg BASE_VERSION=3.9"` this fails with the same message.

### Expected behavior
`extra-build-args` should work to pass `--build-arg` parameters like 7.3.0 did.

**Comment by brivu** [comment]
Hey @iandelahorne, 

Thanks for pointing this issue out. I've addressed this in my next minor version update in PR #187.

Best, 
Brian

**Comment by clementlecorre** [comment]
I have a problem when I use args with bash commands, am I using the wrong syntax? (tested with v8.1.0)

my command:
```
extra-build-args:  --build-arg VERSION="$(cat version.txt)" --build-arg SOURCE="${CIRCLE_REPOSITORY_URL}"
```
my error: 
```
unknown shorthand flag: 'u' in -u
See 'docker buildx build --help'.
```

**Comment by kokizzu** [comment]
@clementlecorre waiting for this fix https://github.com/CircleCI-Public/aws-ecr-orb/pull/193
but meanwhile, you can use 7.3.0

**Comment by trondhindenes** [comment]
is this still broken? That's not a good sign...

**Comment by Andy-Bell** [comment]
Seeing this issue still on any builds that specify their own dockerfile, getting

```
error: "docker buildx build" requires exactly 1 argument.
```

**Comment by sakshamnegi** [comment]
I'm st

> Seeing this issue still on any builds that specify their own dockerfile, getting
> 
> ```
> error: "docker buildx build" requires exactly 1 argument.
> ```

Still seeing the same issue 2 yrs after the fix :/

![image](https://github.com/user-attachments/assets/664ff30f-49c5-41cc-b31a-a58907aa40eb)

**Comment by marboledacci** [comment]
This issue has been closed for more than two years, please create a new one with specific details.
